### ISSUE TITLE
do no support map in struct yet ??

### ISSUE THREAD

**Issue by tsingson** [bet365/jingo#1]
as title......

**Comment by tegk** [comment]
"Maps are currently not supported. Initial thoughts were given that this is a performance focused library it doesn't make much sense to iterate maps and would advise against doing so for performance sensitive applications - however - maps are being added!"

**Comment by godcong** [comment]
decode is not support,too.

**Comment by Humbertzhang** [comment]
Is there a plan to support Unmarshal in this package?

**Comment by mjgarton** [comment]
Is anyone actively working on adding Map support?  If not, I may take a look at adding it, but I don't want to if someone is already actively developing it.

**Comment by kungfusheep** [comment]
Hi @mjgarton - though we're keen to pick it up, there's no work active currently for Map support so do feel free to take a look.

**Comment by johngillott** [comment]
Hi @kungfusheep, I have an implementation to support encoding Maps however it will require go1.12+ as it is dependent on runtime internals. Would you like me to raise MR?

**Comment by kungfusheep** [comment]
@johngillott absolutely, raise the MR.  I'm keen to discuss and see what we've got.  

Though I'm not sure about losing <go.12 support we could potentially maintain an alternate branch which has Map support if the reliance on runtime can't be mitigated.

**Comment by kungfusheep** [comment]
See #19, map support lives on the map_support branch, for now. Thanks to @johngillott for the implementation.
