### ISSUE TITLE
support time.Time serialization

### ISSUE THREAD

**Issue by iivvoo** [bet365/jingo#14]
jingo currently can't serialize time.Time. By default it will serialize to `{}`, and using stringify it won't give a proper ISO8601 (?) representation.

I've attempted to work around this using a fallback to the json.Marshaller interface (see #13 ) but explicitly supporting time.Time is more efficient and probably as effective.

**Comment by kungfusheep** [comment]
Thanks

From https://github.com/bet365/jingo/pull/13#issuecomment-499833806

> The Time package already offers support for AppendFormat([]byte, layout string) []byte, so if we had 1st class support we would be able to do so without the additional alloc needed by MarshalJSON.
>
>I propose adding ptrTimeToBuf(unsafe.Pointer, *Buffer) to ptrconvert.go then adding a hook within the encoders to use that for time.Time.
>
> The function would behave the same way the rest of the append functions in that file behave and would nominate time.RFC3339Nano as the layout. This then puts the output in-line with what you may expect from JSON.stringify within a browser.

**Comment by kungfusheep** [comment]
Cheers @johngillott

**Comment by johngillott** [comment]
No problem 👍  @kungfusheep
